# Generated by Django 5.2 on 2025-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='num_kids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
