# Generated by Django 5.2 on 2025-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_journey_tourday_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_1',
            field=models.URLField(blank=True, help_text='صورة إضافية رقم 1'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_2',
            field=models.URLField(blank=True, help_text='صورة إضافية رقم 2'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_main',
            field=models.URLField(blank=True, help_text='رابط صورة رئيسية للفندق'),
        ),
    ]
