# Generated by Django 5.2.1 on 2025-05-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_image_1_hotel_image_2_hotel_image_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('truck', 'Truck'), ('convertible', 'Convertible')], max_length=100)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزين'), ('diesel', 'ديزل'), ('electric', 'كهرباء'), ('hybrid', 'هايبرد')], max_length=50)),
                ('transmission', models.CharField(choices=[('manual', 'عادي'), ('automatic', 'أوتوماتيك')], max_length=50)),
                ('model_year', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True, help_text='رابط صورة للسيارة')),
            ],
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.car')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
