# Generated by Django 5.2.1 on 2025-05-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_car_carprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.journey')),
            ],
        ),
    ]
