# Generated by Django 5.2.1 on 2025-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_journeyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprice',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
